/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;


 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Baylasan
 */
public class CoffeeMachineFame extends javax.swing.JFrame {
        Coffee c=new Coffee();
         private logger logger;
        
    

    /**
     * Creates new form CoffeeMachineFame
     */
    public CoffeeMachineFame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cofeechoiceComboBox = new javax.swing.JComboBox<>();
        messageLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        caffienButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        fillButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        shotsComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cofeechoiceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espresso", "Americano" }));
        cofeechoiceComboBox.setToolTipText("");
        cofeechoiceComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cofeechoiceComboBoxItemStateChanged(evt);
            }
        });
        cofeechoiceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofeechoiceComboBoxActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        messageLabel.setText("    Select your coffee :    ");

        startButton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        startButton.setText("Start ");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        caffienButton.setFont(new java.awt.Font("Andalus", 0, 12)); // NOI18N
        caffienButton.setText("Calculate calories &caffiene");
        caffienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffienButtonActionPerformed(evt);
            }
        });

        checkButton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        checkButton.setText("Checkc containers ");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        fillButton.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        fillButton.setText("Fill the containers");
        fillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 102, 0));
        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coffee Machine");
        jLabel1.setToolTipText("");

        shotsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 shot", "2 shots" }));
        shotsComboBox.setToolTipText("");
        shotsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shotsComboBoxItemStateChanged(evt);
            }
        });
        shotsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shotsComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(fillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(startButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cofeechoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shotsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caffienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cofeechoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shotsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(caffienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillButton)
                    .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cofeechoiceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofeechoiceComboBoxActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_cofeechoiceComboBoxActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        startButton.addActionListener(cofeechoiceComboBox);
        String selectedcoffee=String.valueOf(cofeechoiceComboBox.getSelectedItem());
            try {
                c.makecoffee(selectedcoffee, shotsComboBox.getSelectedIndex());
            } catch (Exception ex) {
                Logger.getLogger(CoffeeMachineFame.class.getName()).log(Level.SEVERE, null, ex);
            }
        JOptionPane.showMessageDialog(this, "Brewing "+shotsComboBox.getSelectedItem()+" of " + selectedcoffee + "...");
        if (c.getCupscounter()==10) {
            JOptionPane.showMessageDialog(this, "Please clean the water tray and waste bin.");
            this.logger.logInfo("Making coffee");
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void cofeechoiceComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cofeechoiceComboBoxItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cofeechoiceComboBoxItemStateChanged

    private void caffienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffienButtonActionPerformed
        // TODO add your handling code here:
        caffienButton.addActionListener(cofeechoiceComboBox);
        caffienButton.addActionListener(shotsComboBox);
        int x=shotsComboBox.getSelectedIndex()+1;
        c.calculateCaffeineAndCalories(String.valueOf(cofeechoiceComboBox.getSelectedItem()), x);
        this.logger.logInfo("Cafiene and calories calculation");
    }//GEN-LAST:event_caffienButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed

            // TODO add your handling code here:
            JOptionPane.showMessageDialog(this ,"Checking...");
            JOptionPane.showMessageDialog(this, "Beans amount :"+c.getB().getAmount()+
                    "\nWater level :"+c.getW().getWaterlevel());
         this.logger.logInfo("Checking containers");
    }//GEN-LAST:event_checkButtonActionPerformed

    private void fillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillButtonActionPerformed
        // TODO add your handling code here:
        c.FillContainers();
       JOptionPane.showMessageDialog(this,"Beans Container Filled !\nWater Container Fillid !");
       this.logger.logInfo("Filling containers");
    }//GEN-LAST:event_fillButtonActionPerformed

    private void shotsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shotsComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_shotsComboBoxItemStateChanged

    private void shotsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shotsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shotsComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeMachineFame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton caffienButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JComboBox<String> cofeechoiceComboBox;
    private javax.swing.JButton fillButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JComboBox<String> shotsComboBox;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

    private void cofeechoiceComboBox(String[] c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
